### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#1]
Add a Toggle Button and CLI Command to Switch to Dark Mode.

**Comment by Mide001** [comment]
Hi @TechSpiritSS can you assign this issue to me ?

**Comment by TechSpiritSS** [comment]
You got 48hrs 😃

**Comment by YashM246** [comment]
Hey there! Can i work on this as well?

**Comment by TechSpiritSS** [comment]
hey @YashM246 I have already assigned this issue, you can look around and create a new one if you're interested in the project :)

**Comment by subhranshuchoudhury** [comment]
@TechSpiritSS can you please assign me a task?

**Comment by TechSpiritSS** [comment]
Yash is already working on this, If no PR is made by tomorrow, I'll assign you.

**Comment by rkatara100** [comment]
Placing a toggle button to switch between light & dark button.
@TechSpiritSS please assign me this under Hacktoberfest2022.

**Comment by YashM246** [comment]
@TechSpiritSS Hey I am working on this but I wanted to ask if you want the color palette of menu terminal to change as well when we switch to Dark Mode. If yes, do you have a specific color palette in mind?

**Comment by TechSpiritSS** [comment]
@rkatara100 @YashM246  is already working on this.
@YashM246 If you have a good color palette in mind go for it and do look at the color theme PR someone else has made too, I might merge that as it looks promising in that case you have to work according to that merge.

**Comment by YashM246** [comment]
@TechSpiritSS From what I can see in the Pull Requests, the other contributor has added multiple different themes. I am a little confused. I am working on only one dark mode theme. I hope that is alright.

**Comment by YashM246** [comment]
@TechSpiritSS Hey I reviewed the latest merge. His themes makes my Dark Mode Toggle redundant as one of the themes has almost the same color palette. Should I still make a pull request of my original work? Making changes now in the newest merge seems like a waste right now.

**Comment by YashM246** [comment]
@TechSpiritSS Is your site working after the newest merge? I think I'm facing some issues here. The terminal seems to be blank.

**Comment by TechSpiritSS** [comment]
Yes, it's working fine for me.

**Comment by aradhya-10** [comment]
Hey @TechSpiritSS , can I work on this issue?
Contributing for SWOC s3.

**Comment by TechSpiritSS** [comment]
Yes you can

**Comment by aradhya-10** [comment]
@TechSpiritSS I noticed that some of the themes had a dark shade already. I'm considering segregating the themes so that different options appear based on whether the dark mode is turned on or the light. This way users will have different themes for both dark and light modes. Does that work?

**Comment by TechSpiritSS** [comment]
Yup, that's cool to group them according to theme preference.

**Comment by khushigarg1** [comment]
Can You assign this issue to me?

**Comment by TechSpiritSS** [comment]
@aradhya-10 are you still working on this issue?

**Comment by MridulGupta007** [comment]
Hey i know how to create dark mode, pls assign the issue to me

**Comment by TechSpiritSS** [comment]
Dark mode is already there, you have to create command which further ask user which dark mode theme they want to apply. you need to group existing theme into light and dark mode.

**Comment by aradhya-10** [comment]
Hey, I'm done with it, just can't access my laptop right now. Will create a PR tonight.

**Comment by TechSpiritSS** [comment]
Alright, assigning back to you.

**Comment by Siddhesh-Agarwal** [comment]
Is this issue still on? I guess the different themes solve the purpose.

**Comment by TechSpiritSS** [comment]
it's for grouping the themes

**Comment by khushigarg1** [comment]
> it's for grouping the themes

Please assign this issue to me!
