### ISSUE TITLE
[Bug]: 'Tab' Autocomplete not working

### ISSUE THREAD

**Issue by BhagatHarsh** [TechSpiritSS/Terminal-Portfolio#101]
### What happened?

I was working on #99 and while doing so found that after the code refractor the Tab functionality is not working.

### What should have happened?

Whenever we press Tab key the command if related then should be autocompleted.

**Comment by BhagatHarsh** [comment]
I think I know how to fix this. 
assign it to me if you think its an appropriate issue.

**Comment by PiXeL99-eng** [comment]
Right. My bad. I forgot to move the commandsList array from script.js file to eventListeners.js file.
Simply copy pasting that array into the eventListeners.js file will do the job.

Thanks @BhagatHarsh for pointing it out.

**Comment by TechSpiritSS** [comment]
Sorry, I might have missed that.
