### ISSUE TITLE
[Req]: History Command

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#106]
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

This will allows users to view a record of previously executed commands. This feature can be particularly useful for users who need to refer back to past commands or who want to see a record of their activity within the terminal

### Explain the possible use cases for the feature

- Record keeping
- Enhanced user experience

**Comment by BhagatHarsh** [comment]
I would like to work on this issue but need some clarification on this.
are we supposed to save the history just like the theme of the website or just show all the commands performed before, means after the website is closed should the history be saved or deleted.
And any other features like command count of each command (using flags).

**Comment by TechSpiritSS** [comment]
History of the commands given, and it is further stored in the local storage as well

**Comment by BhagatHarsh** [comment]
that makes sense, please assign this to me.
