### ISSUE TITLE
[Req]: Responsiveness

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#108]
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

Currently the site is not fully responsive and has some minor bugs. Fix all those non (or less) responsive elements (including themes).

### Explain the possible use cases for the feature

- Improved accessibility:
- Enhanced user experience

**Comment by khushigarg1** [comment]
Please assign this work to me.

**Comment by TechSpiritSS** [comment]
You can only choose one issue at a time either this or skills command

**Comment by MridulGupta007** [comment]
Hey pls assign the issue to me

**Comment by khushigarg1** [comment]
Please assign this issue to me!
