### ISSUE TITLE
[Req]: Skills Command

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#109]
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

Create a Skill Command to showcase skills. The UI must be clean with proper groups / categories like this
![image](https://user-images.githubusercontent.com/76687985/211168513-e01b6569-0efd-414e-b8d0-81bdca76bc80.png)

Add those skills static data in Config JSON File and you can add any skill you want to ensure all the required groups are been created

**Comment by khushigarg1** [comment]
I would like to work on this issue. Can you assign this issue to me ?

**Comment by TechSpiritSS** [comment]
As soon as your previous experience PR gets merge, I'll assign this to you.

**Comment by khushigarg1** [comment]
> As soon as your previous experience PR gets merge, I'll assign this to you.

Okay Sure!

**Comment by khushigarg1** [comment]
@TechSpiritSS  Now please assign this issue to me.
