### ISSUE TITLE
[Bug]: Minimize Button changing location of the Title Bar

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#111]
### Contact Details

techspiritss@duck.com

### What happened?

![msedge_PRrknPnyqq](https://user-images.githubusercontent.com/76687985/211168684-cf856501-e677-4e69-a0a7-c1c6860979cb.gif)
The bar is moving up on click

### What should have happened?

The bar should remain fixed to its previous position.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by ArnabChatterjee20k** [comment]
assign me this issue. discord username Arnab20k(Gravdestroyer)
