### ISSUE TITLE
[Req]: Minimise lines of code

### ISSUE THREAD

**Issue by harsitagarwalla187** [TechSpiritSS/Terminal-Portfolio#114]
### Explain the proposed feature

In the theme setter file, i want to replace so many lines of if and else statement with two lines.
The page has been tageged below.

https://github.com/TechSpiritSS/Terminal-Portfolio/blob/main/scripts/themeSetter.js

**Comment by harsitagarwalla187** [comment]
Can you assign me this under SWOC 23

**Comment by TechSpiritSS** [comment]
Sure, go for this
