### ISSUE TITLE
Exit command is missing from the list of commands

### ISSUE THREAD

**Issue by siddharthsinghvats** [TechSpiritSS/Terminal-Portfolio#122]
### What happened?

The list of commands does not show exit command , neither using help command shows this option

### What should have happened?

Exit command should be mentioned to enable the users know that they can exit the terminal using exit command.

**Comment by siddharthsinghvats** [comment]
I want to fix this.

**Comment by TechSpiritSS** [comment]
ls, cls and exit commands are left purposefully as Easter eggs.

**Comment by siddharthsinghvats** [comment]
ok thanks
