### ISSUE TITLE
[Req]: Themes

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#125]
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

There's always some extra space for new themes 😃

**Comment by dheerajchhatanidc** [comment]
I want to work for this issue, can u assign it to me? Also, can u elaborate more about this issue.

**Comment by TechSpiritSS** [comment]
this is upto your own creativity, you can create a new theme of your choice

**Comment by khushigarg1** [comment]
I would also like to create theme can you assign this to me?

**Comment by TechSpiritSS** [comment]
You can try adding one afterwards, only one at a time.

**Comment by khushigarg1** [comment]
> You can try adding one afterwards, only one at a time.

Okay sure
