### ISSUE TITLE
[Req]: history {id} command

### ISSUE THREAD

**Issue by VaibhavArora314** [TechSpiritSS/Terminal-Portfolio#126]
### Contact Details

Discord id: vaibhav_#7300

### Explain the proposed feature

Create a history {id} command to run a specific command from the history of a given id.
Please assign me this issue, I am willing to work on it.

Like if a user enters the command: history 1
then it should run the help command for the following history
![image](https://user-images.githubusercontent.com/84830429/211742077-08dfae8f-eeb8-4653-a99f-64e8c460de2e.png)

**Comment by VaibhavArora314** [comment]
hey @TechSpiritSS , can you please assign this to me

**Comment by TechSpiritSS** [comment]
Sure
