### ISSUE TITLE
[Req]: add -d tag to help

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#129]
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

As we are adding new features the help tag is getting messier. The current help tag should only be shown when `help -d` is asked. In case of only `help` show the list of commands as single line.
`about, contribution, calc` and so on.

### Explain the possible use cases for the feature

Cleaner Interface

**Comment by arjun118** [comment]
I Would like to work on this issue, can you please assign this issue to me?

**Comment by khushigarg1** [comment]
I would like to work on this issue.
