### ISSUE TITLE
[Req]: contact edit

### ISSUE THREAD

**Issue by khushigarg1** [TechSpiritSS/Terminal-Portfolio#137]
### Explain the proposed feature

when we type contact on command line it will be show soemthing like this.

![img](https://user-images.githubusercontent.com/84948160/212164210-4389e1b5-4922-4523-b3e7-156ff50221de.png)

**Comment by TechSpiritSS** [comment]
that looks good but it's a part of GUI instead of CLI

**Comment by khushigarg1** [comment]
> that looks good but it's a part of GUI instead of CLI

Oh Okay
