### ISSUE TITLE
[Bug]: Firefox not supporting Import of JS

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#138]
### Contact Details

techspiritss@duck.com

### What happened?

Import in not supported for JS files in Firefox.
![image](https://user-images.githubusercontent.com/76687985/212264513-41b0650e-baf6-4281-863a-5993f7c9b3ee.png)
Old Version of this Terminal is working 

### What should have happened?

It should work as expected in any browser

### What browsers are you seeing the problem on?

Firefox

### Version

108.0.1

**Comment by theanuragshukla** [comment]
hey, assign me this issue. I'm already working on this issue.

**Comment by TechSpiritSS** [comment]
Sure 🚀
