### ISSUE TITLE
Footer gets removed on using 'clear' command

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#14]
The clear command is causing footer removed. Try to fix that by ensuring only the text area of the terminal gets cleaned.

**Comment by AshishRaikwar1290** [comment]
assign me this issue

**Comment by ethandpark** [comment]
I also could take this on if Ashish changes their mind

**Comment by TechSpiritSS** [comment]
> I also could take this on if Ashish changes their mind

In the meantime, you can look for any other bug or create a feature of your own :)
