### ISSUE TITLE
[Bug]: History command not working

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#141]
### Contact Details

techspiritss@duck.com

### What happened?

History command not working due to some faculty PR.

### What should have happened?

Fix the history command

**Comment by dheerajchhatanidc** [comment]
I want to work on the issue, can u assign it to me?

**Comment by TechSpiritSS** [comment]
@dheerajchhatanidc  this bug has been fixed in the latest PR
