### ISSUE TITLE
[Bug]: Possible improvement in speed while using `ls`

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [TechSpiritSS/Terminal-Portfolio#143]
### Contact Details

siddhesh.agarwal@gmail.com

### What happened?

In this [part](https://github.com/TechSpiritSS/Terminal-Portfolio/blob/86e3e02dfc12a1fb4b1771f1974152831d840bbd/scripts/functions.js#L73-L97), instead of adding it in any order and then sorting, we can reorder the list in the correct order to save computation time

### What should have happened?

Add lists in sorted order directly saving compute time.

**Comment by TechSpiritSS** [comment]
Sure, and do the comment to follow the order for other contributors
