### ISSUE TITLE
[Bug]: `calc` is using `eval` directly

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [TechSpiritSS/Terminal-Portfolio#144]
### Contact Details

siddhesh.agarwal@gmail.com

### What happened?

So the `calc` command in the terminal is using `eval()` directly leaving the website open to a range of problems.

![image](https://user-images.githubusercontent.com/68057995/212327059-37c044a0-01bb-4853-b74f-26863786eb1c.png)

### What should have happened?

Apart from math functions, no command should be allowed to be executed without strict mode

**Comment by TechSpiritSS** [comment]
Go for it 🚀
