### ISSUE TITLE
[Req]: Text writing animation

### ISSUE THREAD

**Issue by VaibhavArora314** [TechSpiritSS/Terminal-Portfolio#154]
### Contact Details

Discord id: vaibhav_#7300

### Explain the proposed feature

Add a text-writing animation and a command to turn it off and on.
Ex:

https://user-images.githubusercontent.com/84830429/212622890-731d30b4-d355-4815-98d8-2376f9dc8db2.mp4

Please assign it to me.

**Comment by TechSpiritSS** [comment]
Go for it 🚀

**Comment by TechSpiritSS** [comment]
Remember to add a command as well

**Comment by VaibhavArora314** [comment]
@TechSpiritSS for the cmd, I have added options to turn on and off or set custom typing speed. Should I add/remove any features or is this good enough?
