### ISSUE TITLE
Create buttons to change theme

### ISSUE THREAD

**Issue by ethapar** [TechSpiritSS/Terminal-Portfolio#16]
I'd like to add the ability to change between different color themes, much like what normal terminals have. Maybe start with a few preset ones for now, with the possibility of later adding functionality for the user to create their own?

**Comment by ethandpark** [comment]
I was thinking of having a few circular buttons in the top right that the user could click on and each would change the terminal theme. Of course the image I shared down below isn't the best color combo but it's what I mean about switching themes. Could also maybe add a command that switches themes as well

![image](https://user-images.githubusercontent.com/70242462/193819019-28d95766-69d3-4217-a44e-134a9c488b0b.png)

**Comment by TechSpiritSS** [comment]
Sure, I approve this (yes color scheme isn't good, but I got your point).

**Comment by diwuracreatives** [comment]
@ethandpark  @TechSpiritSS Instead of adding a button why can't we have another command that changes the ui to dark mode it can be "dark" or something.

**Comment by TechSpiritSS** [comment]
@diwuracreatives someone is already working on adding dark mode through dark command, most probably he'll do it by tomorrow.
