### ISSUE TITLE
[Bug]: Showing "sto" in place of "to" in Skills Description

### ISSUE THREAD

**Issue by Shubhodaya** [TechSpiritSS/Terminal-Portfolio#170]
### Contact Details

shubhodayasarkar@gmail.com

### What happened?

- Showing "sto" in place of "to" in skills description part.

![Screenshot (172)](https://user-images.githubusercontent.com/73129588/214670183-dcf7741f-8429-40c4-ae88-a2e046f846d3.png)

### What should have happened?

- It should have shown "to" like this in skills description.

![Screenshot (171)](https://user-images.githubusercontent.com/73129588/214670363-9071c939-9846-4163-9a41-c1a4a6961abb.png)

### Version

Chrome

**Comment by Shubhodaya** [comment]
Please assign it to me.

**Comment by TechSpiritSS** [comment]
Can't have a PR dedicated to a single typo
