### ISSUE TITLE
[Bug]: orientation of social stats not showing properly

### ISSUE THREAD

**Issue by Shubhodaya** [TechSpiritSS/Terminal-Portfolio#173]
### Contact Details

shubhodayasarkar@gmail.com

### What happened?

- When social -d command is given it is showing the wrong orientation with 0 linkedIn connections
- connections:-, rank:-, rating:- looks better if it shows like connections : , rank : , rating : 
- Typo in skills description showing "sto" in place of "to".

![Screenshot (180)](https://user-images.githubusercontent.com/73129588/214845810-9a26e6f0-26cb-4547-8452-b09bfc3d3d6c.png)

![Screenshot (172)](https://user-images.githubusercontent.com/73129588/214846819-0fda4a36-ef5f-4af7-8c32-461444616ac6.png)

### What should have happened?

- Proper orientation.

![Screenshot (179)](https://user-images.githubusercontent.com/73129588/214847006-691b69d8-1537-4004-87b6-a2e75cdb48dc.png)

- Typo fixed from "sto" to "to"

![Screenshot (171)](https://user-images.githubusercontent.com/73129588/214847068-2946def8-29c4-4acb-a179-9e5e85ea5c6a.png)

### Version

Chrome

**Comment by Shubhodaya** [comment]
@TechSpiritSS Can you assign this to me please.

**Comment by TechSpiritSS** [comment]
Sure, go for it 🚀

**Comment by Shubhodaya** [comment]
#176  Check it out , I have fixed it @TechSpiritSS
