### ISSUE TITLE
fix typo on "stating up" to "starting up"

### ISSUE THREAD

**Issue by dreymotoh** [TechSpiritSS/Terminal-Portfolio#2]

**Comment by dreymotoh** [comment]
love the design and the idea behind this portfolio !

**Comment by TechSpiritSS** [comment]
Well, I like your effort of finding this typo, but it would be better if there are more changes rather than a single word. :) You can help with making README better and adding Code_Of_Condutct and I'll consider your PR :)

**Comment by dreymotoh** [comment]
i understand, assign this to me and i will check the others out as well :)
