### ISSUE TITLE
Create a Pull Request Template for the Repo

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#28]
Create a template which will automatically be added to every PR made to this repo.

**Comment by yash6318** [comment]
hey @TechSpiritSS can you assign it to me? I'd love to contribute.

**Comment by TechSpiritSS** [comment]
Add the following in the template.
- Issue number
- Bug / Feature
- Description
- Preview Link (Imp in case of code change)

and you can add anything else too if required :)

**Comment by TechSpiritSS** [comment]
Sure @yash6318

**Comment by aanchalsharmaa1024** [comment]
plz assign it to me

**Comment by TechSpiritSS** [comment]
@aanchalsharmaa1024 you can look for some other task as @yash6318 as completed this.
