### ISSUE TITLE
Adding the Calculator functionality

### ISSUE THREAD

**Issue by KanishkDadhich** [TechSpiritSS/Terminal-Portfolio#34]
Hey @TechSpiritSS .
I've tried adding a calculator functionality to it.
Note :- It can only perform operation on 2 numbers at a time.
It will take 2 numbers as input and then ask which type of operation to be performed.
It can perform operations such as addition, subtraction, subtraction, division, multiplication, modulo, AND, OR on the two given numbers.

I hope it helps.
P.S :- Please go thoroughly through the script.js file because I've made significant changes in it.

Thanks :)

**Comment by TechSpiritSS** [comment]
Sure mate go for it 👍

**Comment by KanishkDadhich** [comment]
Hey @TechSpiritSS . I've made a calculator for this terminal. But I'm not able to create the pull request. This message is being showed "Can’t automatically merge. Don’t worry, you can still create the pull request". And also I've done significant changes in your code. And I'm sure that it may conflict with other commits. Hence I would like to request you to please create a **NEW BRANCH** and then I'll make a pull request to that branch , if you are comfortable with it. Because I've done significant enough changes to it, and I don't want you to get confused in your project  due to the changes made by me. 

Also If you want to see the calculator, Here's the link to my forked repo:
https://github.com/KanishkDadhich/Terminal-Portfolio

Thanks: :)

**Comment by KanishkDadhich** [comment]
Sure. I'll look into this

**Comment by BhagatHarsh** [comment]
Hey @TechSpiritSS I would like to try Implement this feature.
Im thinking Ill use the inbuild Javascript Eval() function instead of the method @KanishkDadhich used.

**Comment by TechSpiritSS** [comment]
Sure go for it 🚀 
but create a seperate JS file as main file is getting a little messy now.
