### ISSUE TITLE
New command : Showing your github stats

### ISSUE THREAD

**Issue by Arun9739** [TechSpiritSS/Terminal-Portfolio#37]
- I want to add a new command which shows your github stats
- I want to name the command as "stats" (If you want any other name plz tell)
- I will display all your github details as such number of projects, no. of PR's, no. of stars etc.
- I will update the Help command accordingly

**Comment by Arun9739** [comment]
Please assign me this issue under Hacktoberfest

**Comment by TechSpiritSS** [comment]
Sure, go for it 👍

**Comment by coodos** [comment]
@TechSpiritSS Can I take this issue up please?

**Comment by TechSpiritSS** [comment]
Sure @coodos
