### ISSUE TITLE
Add tab autocomplete feature

### ISSUE THREAD

**Issue by N-Shar-ma** [TechSpiritSS/Terminal-Portfolio#38]
To make the terminal UI behave even more like a terminal, I think providing functionality where on pressing tab after an incomplete command, it autocompletes it, would be great!

For example if a user types in `proj` and presses tab, it should update to `project `, after which the user can press Enter to execute the autocompleted command.

If this sounds good to you, I'd love to work on adding this!

**Comment by TechSpiritSS** [comment]
That's a great feature, go for this 👍
