### ISSUE TITLE
Bug: clicking up arrow moves cursor to the beginning

### ISSUE THREAD

**Issue by michelle-salt** [TechSpiritSS/Terminal-Portfolio#39]
In a normal terminal, if you want to go back to a previous command, you can use the up arrow key and it will put the cursor at the end of the previous command typed.

This website has a similar functionality, but puts the cursor at the beginning of the command, which can be annoying if you want to add onto the command

I'd like to try fixing this bug if I can!

**Comment by TechSpiritSS** [comment]
Sure, go for this :+1

**Comment by TechSpiritSS** [comment]
@michelle-salt are you still working on this?

**Comment by rjrishika** [comment]
I want to work on this issue, please assign me if it's available

**Comment by TechSpiritSS** [comment]
Sure @rjrishika

**Comment by PiXeL99-eng** [comment]
@TechSpiritSS I have found a fix for this. Can u assign me this issue? (applicant for SWOC)

**Comment by TechSpiritSS** [comment]
Sure go for it
