### ISSUE TITLE
Adding a favicon to the site

### ISSUE THREAD

**Issue by grlcodr** [TechSpiritSS/Terminal-Portfolio#4]
I would like to add a favicon for the website, I have designed something that I think is appropriate - a terminal icon, in the main color of the website! 

<img width="100" alt="Screenshot 2022-10-03 at 19 48 46" src="https://user-images.githubusercontent.com/74377431/193655170-4b9773ea-3c52-4420-89b1-505e3b60da80.png">

And the following is an example of how that would look in a browser tab:
<img width="131" alt="Screenshot 2022-10-03 at 19 50 11" src="https://user-images.githubusercontent.com/74377431/193655450-608142a8-1289-4949-864c-6f5e2b2f0671.png">

Please let me know if this is acceptable and I will add for Hacktoberfest ☺️

**Comment by TechSpiritSS** [comment]
you have created this favicon yourself?

**Comment by grlcodr** [comment]
I have - it was created using the website [favicon.cc](https://favicon.cc) that allows you to draw pixel type icons in any colours you'd like and download for usage!

**Comment by TechSpiritSS** [comment]
Great One 👍
