### ISSUE TITLE
Bug: up arrow goes to the second most recent command

### ISSUE THREAD

**Issue by michelle-salt** [TechSpiritSS/Terminal-Portfolio#40]
When clicking the up arrow, I expect the most recent entered command to appear, however the second most recent command appears instead. This only happens when more than one command was entered.

I'd like to try working on this issue, if I can

**Comment by TechSpiritSS** [comment]
Sure, go for it 👍

**Comment by TechSpiritSS** [comment]
@michelle-salt are you still working on this?
