### ISSUE TITLE
[Req]: Dropdown Menu for Theme Switcher

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#45]
### Explain the proposed feature

Make a drop-down menu for theme switcher that can act in both UI (Desktop and Mobile).

### Any other details you would like to provide?

The Mobile UI should remain clean.

**Comment by TechSpiritSS** [comment]
@ethapar would you like to proceed with this?

**Comment by ethapar** [comment]
Yeah I can take this on!

**Comment by TechSpiritSS** [comment]
Go for this 👍

**Comment by siddharthsinghvats** [comment]
I want to work on this dropdown
