### ISSUE TITLE
Add a command for showing contributors names.

### ISSUE THREAD

**Issue by subhranshuchoudhury** [TechSpiritSS/Terminal-Portfolio#46]
As we know the development of the project clearly depends upon the contributors. We should add a command for it. If you assign then i will add the command.

**Comment by TechSpiritSS** [comment]
That's a great idea but how would you ensure that the list gets updates automatically every time someone makes a contribution?

**Comment by subhranshuchoudhury** [comment]
By using cherrio ( web scraper ) or using native github api.

**Comment by TechSpiritSS** [comment]
well in that case go for it :)

**Comment by subhranshuchoudhury** [comment]
@TechSpiritSS i did a PR kindly review it.

**Comment by TechSpiritSS** [comment]
Done :)
