### ISSUE TITLE
[Req]: Separate Files

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#50]
### Explain the proposed feature

The code files are getting bigger and it's getting difficult to keep track of all the code in single file. It'd be better if we spilt the files according to the job, they are preforming instead of having all in one file.

**Comment by Petsamuel** [comment]
Having a well structed folder for Storing CSS styles, and javascript in another file makes the HTML file more concise and organized.

I would like to work on this issue, pls assign it to me

**Comment by TechSpiritSS** [comment]
@manav-06 Go for it 👍 and try to make this a today itself as it may cause merge conflicts.
Sorry @Petsamuel I have to give this one to @manav-06 as manav approached first, you can look for some bug and add your own feature in the meantime :)

**Comment by Petsamuel** [comment]
oh alright

**Comment by PiXeL99-eng** [comment]
@TechSpiritSS I was wondering if I could work on this issue. The entire page is made in JS, which makes it lengthy. How do you want to break down the page? Should I make it into separate JS files, 
keydown functions, 
fetchStats functions, 
power buttons (green, yellow & red) 
setup functions?

**Comment by TechSpiritSS** [comment]
Sure, go for it  🚀

**Comment by PiXeL99-eng** [comment]
Hey @TechSpiritSS . I noticed, in the script.js file, fetchGithubStats() function is defined twice... Once in line 84 and again in line 457... Currently the second function is active. Do you want me to remove the first instance?

**Comment by TechSpiritSS** [comment]
in that case eliminate that dead function out.

**Comment by PiXeL99-eng** [comment]
Gotcha

**Comment by PiXeL99-eng** [comment]
Hey @TechSpiritSS . I have almost finished this work. Divided the entire script.js into multiple separate JS files, which have similar functions in each file. Each JS file is imported into the main script.js file.

So, the Upcoming PR will alter the codebase to some good extent. So, I am pretty sure, other contributors must pull the new code-base before they can proceed with their changes. What are your thoughts on this?

**Comment by TechSpiritSS** [comment]
Yes, I agree that other contributors are required to follow the same system, I'll be pausing more PR after this comment
Try to cover all updates till now in this split file PR.

**Comment by PiXeL99-eng** [comment]
Ok. I will try my best to finish this work by today.
