### ISSUE TITLE
[Bug]: Change EXIT from Click to Type

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#53]
### What happened?

The EXIT works on mouse click. 

### What should have happened?

Change that clicks to exit to Type to exit i.e., user type EXIT to EXIT the window.

**Comment by AshishRaikwar1290** [comment]
assign me this issue

**Comment by TechSpiritSS** [comment]
Sure

**Comment by gaut2003** [comment]
Here there is a problem that a window or a tab can be closed if and only if that window or tab was opened using Javascript.
I can work on this by finding any alternate way to exit from that tab or redirect to another tab.

**Comment by TechSpiritSS** [comment]
That's great @gaut2003 but I have already assigned @AshishRaikwar1290 on this issue :).
And for Exit there is already a code present in the terminal which act as an exit command, and I want to relocate that from terminal to buttons,
