### ISSUE TITLE
[Req]: Add a command to download resume

### ISSUE THREAD

**Issue by muskanbararia** [TechSpiritSS/Terminal-Portfolio#62]
### Contact Details

muskanbararia@gmail.com

### Explain the proposed feature

Add a new command that will download the resume in pdf format.

**Comment by muskanbararia** [comment]
would want to work on it under hacktoberfest

**Comment by TechSpiritSS** [comment]
Go for it 👍

**Comment by ankitrout2903** [comment]
can i do it under hacktober fest

**Comment by TechSpiritSS** [comment]
Sure @ankitrout2903

**Comment by SattyamSamania** [comment]
Hey @TechSpiritSS Can I work on this also tell me further what to do next.

**Comment by TechSpiritSS** [comment]
You can add sample PDF Link in JSON File and create a Download or Resume Command to download the Resume PDF File upon typing the command in the terminal

**Comment by SattyamSamania** [comment]
@TechSpiritSS In the html file where should I add the button to link to the resume?

**Comment by TechSpiritSS** [comment]
There should be no buttons all commands line interface, you have to set a command instead of buttons.

**Comment by SattyamSamania** [comment]
@TechSpiritSS sure.

**Comment by SattyamSamania** [comment]
> There should be no buttons all commands line interface, you have to set a command instead of buttons.

@TechSpiritSS Can I still work on this if I have not selected this project in SWOC?

**Comment by TechSpiritSS** [comment]
Yes, but it won't be counted for SWOC if you haven't selected it

**Comment by PiXeL99-eng** [comment]
I have selected it already. Creating a PR.

**Comment by TechSpiritSS** [comment]
Currently it is assigned to @SattyamSamania, you can ping him on discord and ask if he's having difficulties in implementing this I can re-assign this to you.

**Comment by SattyamSamania** [comment]
> Currently it is assigned to @SattyamSamania, you can ping him on discord and ask if he's having difficulties in implementing this I can re-assign this to you.

@TechSpiritSS you can unassign me as I am having my exams so cannot give time. Thank you 😊

**Comment by TechSpiritSS** [comment]
Sure, good luck for your exams 👍

**Comment by SattyamSamania** [comment]
> Sure, good luck for your exams 👍

@TechSpiritSS Thank you 😊
