### ISSUE TITLE
[Req]: Ctrl+L clears the terminal instead of typing "clear"

### ISSUE THREAD

**Issue by kuberaspeaking** [TechSpiritSS/Terminal-Portfolio#68]
### Contact Details

kuber.shruti@gmail.com

### Explain the proposed feature

In an terminal, pressing Ctrl+L clears the terminal. Would like to implement the same to give enhance the terminal like experience. 

### Explain the possible use cases for the feature

For someone who uses the terminal regularly, the user would want the same experience as with a real terminal. 

### Any other details you would like to provide?

Would like to do this for hacktoberfest. Would be great if you could assign it to me.

**Comment by TechSpiritSS** [comment]
Sure, you can go for this but don't remove clear keywords as well :)
