### ISSUE TITLE
[Req]: Store the user theme preference to the local storage

### ISSUE THREAD

**Issue by BiswajitSahoo-tech** [TechSpiritSS/Terminal-Portfolio#70]
### Contact Details

sahoosipun834@gmail.com

### Explain the proposed feature

Every time after refreshing the webpage, the theme gets set to the default one. Rather than this, it should remember the user preference and load the theme that is chosen by the user whenever the user visits the webpage.

### Explain the possible use cases for the feature

Suppose I will visit the webpage after months, even after so long time the webpage directly loads into my preferred theme that I may had choose months ago.

**Comment by TechSpiritSS** [comment]
Cool, go for it 👍
