### ISSUE TITLE
[Bug]: Fix case sensitivity

### ISSUE THREAD

**Issue by stallardjw** [TechSpiritSS/Terminal-Portfolio#72]
### What happened?

Currently, it only accepts input if it matches the provided commands precisely. it throws an error if there are any uppercase characters or leading and/or trailing spaces.

### What should have happened?

Valid commands should be accepted regardless of their format.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by TechSpiritSS** [comment]
Great 👍 Thanks for looking up this issue :)
