### ISSUE TITLE
[Bug]: Blogs command should be async

### ISSUE THREAD

**Issue by SadashayKanungo** [TechSpiritSS/Terminal-Portfolio#76]
### Contact Details

sadashay01@gmail.com

### What happened?

The `blogs` command fetches an api to get list of blogs. In the current code, this fetch is not done asynchronously. So we are getting the output after a new line has been created in the terminal.
Here is the screenshot of the bug.

![image](https://user-images.githubusercontent.com/51871759/194707463-7e5c0f77-58d5-49ec-ae52-e890ee2fcd3a.png)

### What should have happened?

The api needs to be fetched asynchronously and new line should be created only after the blogs list has been displayed.

**Comment by SadashayKanungo** [comment]
@TechSpiritSS I would like to work on this. Please assign it to me.

**Comment by TechSpiritSS** [comment]
Go for it 👍
