### ISSUE TITLE
[Bug]: Github command should be asynchronous

### ISSUE THREAD

**Issue by SadashayKanungo** [TechSpiritSS/Terminal-Portfolio#81]
### Contact Details

sadashay01@gmail.com

### What happened?

The `github` command fetches the github api to get a user's details. In the current code, this fetch is not done asynchronously. So we are getting the output after a new line has been created in the terminal.
Here is the screenshot of the bug.
![issue](https://user-images.githubusercontent.com/51871759/194817630-28c19993-996d-4c34-aa3e-ac914db55a14.png)

### What should have happened?

The github user details should be prefetched. When `github` command is entered, the only activity should be printing the prefetched details since new line creation is implemented with fixed time delay. This is the implementation style used in `contributors` command that does have this issue.

**Comment by SadashayKanungo** [comment]
Hey @TechSpiritSS please assign this issue to me.

**Comment by TechSpiritSS** [comment]
Sure👍
