### ISSUE TITLE
 fixing typos and add customization to contribuion.md

### ISSUE THREAD

**Issue by Shubh08am** [TechSpiritSS/Terminal-Portfolio#91]
### Explain the proposed feature

Would like to fix typos and try to add customization in contribuion.md

**Comment by TechSpiritSS** [comment]
one or two typo might not be considered as a valid contribution to the project

**Comment by arjun118** [comment]
I would like to contribute to this, but can't get a hang of it. Can you please explain?
Thanks!

**Comment by khushigarg1** [comment]
I would like to work on this issue can you assign it to me ?
