### ISSUE TITLE
[Req]: To sync the background of theme dropdown 

### ISSUE THREAD

**Issue by siddharthsinghvats** [TechSpiritSS/Terminal-Portfolio#93]
### Explain the proposed feature

The theme dropdown should have same background as the current theme.

### Explain the possible use cases for the feature

Will look more inherent.

### Any other details you would like to provide?

No

**Comment by siddharthsinghvats** [comment]
Would like to fix this

**Comment by TechSpiritSS** [comment]
Sure go for it 🚀
