### ISSUE TITLE
Possible command option on wrong command

### ISSUE THREAD

**Issue by TechSpiritSS** [TechSpiritSS/Terminal-Portfolio#99]
### Contact Details

Sidharth.sherry@gmail.com

### Explain the proposed feature

On inputting wrong command, instead of simply stating wrong command, it can show possible command for example.
Input - `Githb`
Output - do you mean `Github`?

### Explain the possible use cases for the feature

This will make Terminal more user friendly while stating the possible typo

### Any other details you would like to provide?

Make sure the operation isn't resource expensive to cause some kind of lags.

**Comment by BhagatHarsh** [comment]
I would like to work on this issue.
I imagine it would be the same as the one that we are using with the 'Tab' press.
where the user has only entered a fraction of code and then using .startsWith we are able to autocomplete the message
similarly we can also show the possible commands that could have been selected.

**Comment by TechSpiritSS** [comment]
Sure, the Algorithms will be kind of similar to look for most similar option.
